<?php

namespace App\Controllers\Admin;

use App\Controllers\BaseController;
use Config\Database;

class ReportsController extends BaseController
{
    public function index()
    {
        return view('admin/reports');
    }

    public function exportAdmitted()
    {
        $branch = $this->request->getGet('branch');
        if (!$branch) return redirect()->back()->with('error', 'Branch is required');

        $db = Database::connect();
        // Memory optimized: Only selecting required fields
        $builder = $db->table('spot_registrations')
                      ->select('entrance_rank, entrance_roll_no, full_name, mobile_no, eligible_category, allotted_course')
                      ->where('status', 'submitted')
                      ->where('allotted_course', $branch)
                      ->orderBy('entrance_rank', 'ASC');

        return $this->streamCsv($builder, 'admitted_students_' . $branch);
    }

    public function exportApplied()
    {
        $branch = $this->request->getGet('branch');
        $format = $this->request->getGet('format');
        if (!$branch) return redirect()->back()->with('error', 'Branch is required');

        if ($format === 'pdf') {
            return $this->exportAppliedPdf($branch);
        }

        $db = Database::connect();
        // Memory optimized: Only selecting required fields
        $builder = $db->table('spot_registrations')
                      ->select('entrance_rank, entrance_roll_no, full_name, mobile_no, eligible_category, option_1, option_2, option_3, option_4, option_5, option_6, option_7')
                      ->where('status', 'submitted')
                      ->groupStart()
                          ->where('option_1', $branch)
                          ->orWhere('option_2', $branch)
                          ->orWhere('option_3', $branch)
                          ->orWhere('option_4', $branch)
                          ->orWhere('option_5', $branch)
                          ->orWhere('option_6', $branch)
                          ->orWhere('option_7', $branch)
                      ->groupEnd()
                      ->orderBy('entrance_rank', 'ASC');

        $this->setupCsvHeaders('applied_students_' . $branch);
        $out = fopen('php://output', 'w');

        // ── Metadata Header ──
        fputcsv($out, ['Mar Athanasius College of Engineering, Kothamangalam']);
        fputcsv($out, ['B.Tech Admission Portal']);
        fputcsv($out, ['Applied Students Report']);
        fputcsv($out, ['Branch:', $branch]);
        fputcsv($out, ['Date of Export:', date('d-M-Y H:i:s')]);
        fputcsv($out, ['Generated by:', 'MACE Admission Portal (macesoft.in)']);
        fputcsv($out, []); // blank separator row

        // ── Column Headers ──
        fputcsv($out, ['KEAM Rank', 'Roll No', 'Name', 'Mobile', 'Category', 'Option Preference']);

        $query = $builder->get();
        
        // CRITICAL MEMORY OPTIMIZATION: getUnbufferedRow() fetches 1 row from SQL at a time
        while ($row = $query->getUnbufferedRow('array')) {
            $pref = null;
            for ($i = 1; $i <= 7; $i++) {
                if ($row['option_' . $i] === $branch) {
                    $pref = $i;
                    break;
                }
            }
            fputcsv($out, [
                $row['entrance_rank'],
                $row['entrance_roll_no'],
                $row['full_name'],
                $row['mobile_no'],
                $row['eligible_category'],
                $pref
            ]);
        }
        fclose($out);
        exit();
    }

    private function exportAppliedPdf(string $branch)
    {
        $db = Database::connect();
        $builder = $db->table('spot_registrations')
                      ->select('entrance_rank, full_name, mobile_no, option_1, option_2, option_3, option_4, option_5, option_6, option_7')
                      ->where('status', 'submitted')
                      ->groupStart()
                          ->where('option_1', $branch)
                          ->orWhere('option_2', $branch)
                          ->orWhere('option_3', $branch)
                          ->orWhere('option_4', $branch)
                          ->orWhere('option_5', $branch)
                          ->orWhere('option_6', $branch)
                          ->orWhere('option_7', $branch)
                      ->groupEnd()
                      ->orderBy('entrance_rank', 'ASC');
                      
        $query = $builder->get();
        $applicants = [];
        
        while ($row = $query->getUnbufferedRow('array')) {
            $pref = null;
            for ($i = 1; $i <= 7; $i++) {
                if ($row['option_' . $i] === $branch) {
                    $pref = $i;
                    break;
                }
            }
            $applicants[] = [
                'rank' => $row['entrance_rank'],
                'name' => $row['full_name'],
                'mobile' => $row['mobile_no'],
                'pref' => $pref
            ];
        }

        $html = view('admin/pdf_applied', [
            'branch' => $branch,
            'applicants' => $applicants,
            'date' => date('d-M-Y H:i:s')
        ]);

        $options = new \Dompdf\Options();
        $options->set('isRemoteEnabled', true); // Required to load logo from URL
        
        $dompdf = new \Dompdf\Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        
        $dompdf->stream('mace_applied_students_' . $branch . '_' . date('Ymd_His') . '.pdf', ["Attachment" => false]);
        exit();
    }
    
    public function exportAll()
    {
        $db = Database::connect();
        // Memory optimized: Only selecting required fields
        $builder = $db->table('spot_registrations')
                      ->select('entrance_rank, entrance_roll_no, full_name, mobile_no, email, eligible_category, admitted_elsewhere, present_college, present_branch, has_noc, has_tc_cc, option_1, option_2, option_3, option_4, option_5, option_6, option_7, allotted_course, registered_at')
                      ->where('status', 'submitted')
                      ->orderBy('entrance_rank', 'ASC');
                      
        return $this->streamCsv($builder, 'all_registrations', 'All Registrations');
    }

    private function setupCsvHeaders(string $filenamePrefix)
    {
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="mace_' . $filenamePrefix . '_' . date('Ymd_His') . '.csv"');
        header('Pragma: no-cache');
        header('Expires: 0');
    }

    private function streamCsv($builder, string $filenamePrefix, string $reportTitle = 'Admitted Students Report', string $branch = '')
    {
        $this->setupCsvHeaders($filenamePrefix);
        $out = fopen('php://output', 'w');

        // ── Metadata Header ──
        fputcsv($out, ['Mar Athanasius College of Engineering, Kothamangalam']);
        fputcsv($out, ['B.Tech Admission Portal']);
        fputcsv($out, [$reportTitle]);
        if ($branch) fputcsv($out, ['Branch:', $branch]);
        fputcsv($out, ['Date of Export:', date('d-M-Y H:i:s')]);
        fputcsv($out, ['Generated by:', 'MACE Admission Portal (macesoft.in)']);
        fputcsv($out, []); // blank separator row
        
        $query = $builder->get();
        $isFirstRow = true;

        // CRITICAL MEMORY OPTIMIZATION: getUnbufferedRow()
        while ($row = $query->getUnbufferedRow('array')) {
            if ($isFirstRow) {
                fputcsv($out, array_keys($row));
                $isFirstRow = false;
            }
            
            // Format booleans nicely if present
            if (isset($row['admitted_elsewhere'])) $row['admitted_elsewhere'] = $row['admitted_elsewhere'] ? 'Yes' : 'No';
            if (isset($row['has_noc'])) $row['has_noc'] = $row['has_noc'] !== null ? ($row['has_noc'] ? 'Yes' : 'No') : 'N/A';
            if (isset($row['has_tc_cc'])) $row['has_tc_cc'] = $row['has_tc_cc'] !== null ? ($row['has_tc_cc'] ? 'Yes' : 'No') : 'N/A';
            
            fputcsv($out, array_values($row));
        }
        
        if ($isFirstRow) {
            fputcsv($out, ['No records found']);
        }

        fclose($out);
        exit();
    }
}
